[package]
name = "noir-sidecar"
version = "0.1.0"
authors = ["code0xff <ian.jungyong.um@gmail.com>"]
repository = "https://github.com/NoirHQ/noir-sidecar"
description = "Noir SDK sidecar"
license = "Apache-2.0"
edition = "2024"

[lib]
name = "noir_sidecar"
path = "src/lib.rs"

[[bin]]
name = "noir_sidecar"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.8.19"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
