[server]
listen_address = "127.0.0.1"
port = 8080
cors = "all"
request_timeout_seconds = 120

[client]
endpoint = "ws://127.0.0.1:9944"
request_timeout_seconds = 30
connection_timeout_seconds = 30

[sqlite]
path = "sidecar.db"
